name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers (optional)
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Log in to Docker Hub using token
      - name: Log in to Docker Hub using token
        run: |
          echo "dckr_pat_iqXb_AijlG18dGAz1_dG2ztXw9w" | docker login -u ismail039 --password-stdin

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t soulaimandockerhub/fplarache-smartlib-recommandation:v1.11 .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push soulaimandockerhub/fplarache-smartlib-recommandation:v1.11

      # Optional Step: Run Docker container locally (optional)
      - name: Run Docker container locally (optional)
        run: |
          docker run -d -p 8080:8080 -p 9999:9999 soulaimandockerhub/fplarache-smartlib-recommandation:v1.11
